# Generated by Django 3.2.2 on 2021-05-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=30)),
                ('ulica', models.CharField(max_length=30)),
                ('nr_budynku', models.CharField(max_length=10)),
                ('nr_lokalu', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'adresy',
            },
        ),
        migrations.CreateModel(
            name='DomySeniora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=10)),
                ('krs', models.CharField(max_length=10)),
                ('adresy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.adresy')),
            ],
            options={
                'db_table': 'domy_seniora',
            },
        ),
        migrations.CreateModel(
            name='Lozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_antyodlezynowe', models.CharField(max_length=1)),
                ('dlugosc', models.BigIntegerField()),
                ('opis', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lozka',
            },
        ),
        migrations.CreateModel(
            name='Poczty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_poczty', models.CharField(max_length=6, unique=True)),
                ('poczta', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'poczty',
            },
        ),
        migrations.CreateModel(
            name='Pokoje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pietro', models.BigIntegerField()),
                ('pojemnosc', models.BigIntegerField()),
                ('oblozenie', models.BigIntegerField()),
                ('standard', models.CharField(max_length=10)),
                ('czy_przystosowany_do_wozka', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pokoje',
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('zdjecie', models.BinaryField(blank=True, null=True)),
                ('data_zatrudnienia', models.DateField()),
                ('pesel', models.CharField(blank=True, max_length=11, null=True)),
                ('telefon', models.CharField(max_length=11)),
                ('numer_konta', models.CharField(blank=True, max_length=26, null=True)),
                ('adres_email', models.CharField(max_length=100)),
                ('adresy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.adresy')),
                ('domyseniora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.domyseniora')),
            ],
            options={
                'db_table': 'pracownicy',
            },
        ),
        migrations.CreateModel(
            name='RodzajeLekow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'rodzaje_lekow',
            },
        ),
        migrations.CreateModel(
            name='Stanowiska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'stanowiska',
            },
        ),
        migrations.CreateModel(
            name='Wynagrodzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('kwota_podstawowa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kwota_dodatkowa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pracownicy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.pracownicy')),
            ],
            options={
                'db_table': 'wynagrodzenia',
            },
        ),
        migrations.CreateModel(
            name='Seniorzy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('zdjecie', models.BinaryField(blank=True, null=True)),
                ('domyseniora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.domyseniora')),
                ('lozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.lozka')),
            ],
            options={
                'db_table': 'seniorzy',
            },
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='stanowiska',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.stanowiska'),
        ),
        migrations.AddField(
            model_name='lozka',
            name='pokoje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.pokoje'),
        ),
        migrations.CreateModel(
            name='Leki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('producent', models.CharField(max_length=100)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('ilosc_opakowan', models.BigIntegerField()),
                ('domyseniora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.domyseniora')),
                ('rodzjelekow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.rodzajelekow')),
            ],
            options={
                'db_table': 'leki',
            },
        ),
        migrations.CreateModel(
            name='KartyZdrowia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupa_krwi', models.CharField(max_length=2)),
                ('czynnik_rh', models.CharField(max_length=1)),
                ('uczulenia', models.CharField(blank=True, max_length=500, null=True)),
                ('choroby', models.CharField(blank=True, max_length=500, null=True)),
                ('leki', models.ManyToManyField(to='database.Leki')),
                ('seniorzy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.seniorzy')),
            ],
            options={
                'db_table': 'karty_zdrowia',
            },
        ),
        migrations.AddField(
            model_name='adresy',
            name='poczty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.poczty'),
        ),
    ]
