# Generated by Django 3.2.2 on 2021-05-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leki',
            old_name='rodzjelekow',
            new_name='rodzajelekow',
        ),
    ]
