# Generated by Django 3.2.2 on 2021-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_rodzjelekow_leki_rodzajelekow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresy',
            options={'verbose_name_plural': 'adresy'},
        ),
        migrations.AlterModelOptions(
            name='domyseniora',
            options={'verbose_name_plural': 'domy_seniora'},
        ),
        migrations.AlterModelOptions(
            name='kartyzdrowia',
            options={'verbose_name_plural': 'karty_zdrowia'},
        ),
        migrations.AlterModelOptions(
            name='leki',
            options={'verbose_name_plural': 'leki'},
        ),
        migrations.AlterModelOptions(
            name='lozka',
            options={'verbose_name_plural': 'lozka'},
        ),
        migrations.AlterModelOptions(
            name='poczty',
            options={'verbose_name_plural': 'poczty'},
        ),
        migrations.AlterModelOptions(
            name='pokoje',
            options={'verbose_name_plural': 'pokoje'},
        ),
        migrations.AlterModelOptions(
            name='pracownicy',
            options={'verbose_name_plural': 'pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='rodzajelekow',
            options={'verbose_name_plural': 'rodzaje_lekow'},
        ),
        migrations.AlterModelOptions(
            name='seniorzy',
            options={'verbose_name_plural': 'seniorzy'},
        ),
        migrations.AlterModelOptions(
            name='stanowiska',
            options={'verbose_name_plural': 'stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='wynagrodzenia',
            options={'verbose_name_plural': 'wynagrodzenia'},
        ),
        migrations.AlterField(
            model_name='kartyzdrowia',
            name='leki',
            field=models.ManyToManyField(blank=True, to='database.Leki'),
        ),
    ]
