# Generated by Django 3.2.2 on 2021-05-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210522_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartyzdrowia',
            name='seniorzy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.seniorzy'),
        ),
    ]
