# Generated by Django 3.2.2 on 2021-05-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_kartyzdrowia_seniorzy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresy',
            name='poczty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.poczty'),
        ),
        migrations.AlterField(
            model_name='domyseniora',
            name='adresy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.adresy'),
        ),
        migrations.AlterField(
            model_name='seniorzy',
            name='lozka',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.lozka'),
        ),
    ]
