# Generated by Django 3.2.2 on 2021-05-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210522_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresy',
            name='poczty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='database.poczty'),
        ),
    ]
