# Generated by Django 3.2.2 on 2021-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210524_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokoje',
            name='standard',
            field=models.CharField(choices=[('w', 'Waiting for confirmation'), ('c', 'Confirmed'), ('p', 'Paid')], max_length=10),
        ),
    ]
