# Generated by Django 3.2.2 on 2021-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_pokoje_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartyzdrowia',
            name='czynnik_rh',
            field=models.CharField(choices=[('-', '-'), ('+', '+')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kartyzdrowia',
            name='grupa_krwi',
            field=models.CharField(choices=[('AB', 'AB'), ('A', 'A'), ('B', 'B'), ('0', '0')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lozka',
            name='czy_antyodlezynowe',
            field=models.CharField(choices=[('T', 'Tak'), ('N', 'Nie')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pokoje',
            name='czy_przystosowany_do_wozka',
            field=models.CharField(choices=[('T', 'Tak'), ('N', 'Nie')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pokoje',
            name='standard',
            field=models.CharField(choices=[('standard', 'Standard'), ('wysoki', 'Wysoki'), ('premium', 'Premium')], max_length=10),
        ),
    ]
