# Generated by Django 3.2.2 on 2021-05-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresy',
            fields=[
                ('id_adresu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(max_length=30)),
                ('ulica', models.CharField(max_length=30)),
                ('nr_budynku', models.CharField(max_length=10)),
                ('nr_lokalu', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'adresy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomySeniora',
            fields=[
                ('id_domu_seniora', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=10)),
                ('krs', models.CharField(max_length=10)),
                ('id_adresu', models.BigIntegerField()),
            ],
            options={
                'db_table': 'domy_seniora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KartyZdrowia',
            fields=[
                ('id_karty', models.BigIntegerField(primary_key=True, serialize=False)),
                ('grupa_krwi', models.CharField(max_length=2)),
                ('czynnik_rh', models.CharField(max_length=1)),
                ('uczulenia', models.CharField(blank=True, max_length=500, null=True)),
                ('choroby', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'karty_zdrowia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriePrawaJazdy',
            fields=[
                ('id_kategorii', models.BigIntegerField(primary_key=True, serialize=False)),
                ('kod_kategorii', models.CharField(max_length=4, unique=True)),
                ('opis', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'kategorie_prawa_jazdy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leki',
            fields=[
                ('id_leku', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=40)),
                ('producent', models.CharField(max_length=100)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('ilosc_opakowan', models.BigIntegerField()),
            ],
            options={
                'db_table': 'leki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lozka',
            fields=[
                ('id_lozka', models.BigIntegerField(primary_key=True, serialize=False)),
                ('czy_antyodlezynowe', models.CharField(max_length=1)),
                ('dlugosc', models.BigIntegerField()),
                ('opis', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lozka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marki',
            fields=[
                ('id_marki', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'marki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id_modelu', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'modele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsobaKontaktowaSenior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_osoby', models.BigIntegerField()),
                ('id_seniora', models.BigIntegerField()),
            ],
            options={
                'db_table': 'osoba_kontaktowa_senior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsobyKontaktowe',
            fields=[
                ('id_osoby', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=11)),
                ('adres_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'osoby_kontaktowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poczty',
            fields=[
                ('id_poczty', models.BigIntegerField(primary_key=True, serialize=False)),
                ('kod_poczty', models.CharField(max_length=6, unique=True)),
                ('poczta', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'poczty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pojazdy',
            fields=[
                ('id_pojazdu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numer_rejestracyjny', models.CharField(max_length=7)),
                ('pojemnosc', models.BigIntegerField()),
                ('czy_przystosowany_do_wozka', models.CharField(max_length=1)),
                ('przebieg', models.BigIntegerField()),
                ('data_nastepnego_przegladu', models.DateField()),
                ('opis_stanu', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'pojazdy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pokoje',
            fields=[
                ('id_pokoju', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pietro', models.BigIntegerField()),
                ('pojemnosc', models.BigIntegerField()),
                ('oblozenie', models.BigIntegerField()),
                ('standard', models.CharField(max_length=10)),
                ('czy_przystosowany_do_wozka', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pokoje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id_pracownika', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('zdjecie', models.BinaryField(blank=True, null=True)),
                ('data_zatrudnienia', models.DateField()),
                ('pesel', models.CharField(blank=True, max_length=11, null=True)),
                ('telefon', models.CharField(max_length=11)),
                ('numer_konta', models.CharField(blank=True, max_length=26, null=True)),
                ('adres_email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pracownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrzyjmowaneLeki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leku', models.BigIntegerField()),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('dawka', models.CharField(max_length=100)),
                ('czestotliwosc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'przyjmowane_leki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RodzajeLekow',
            fields=[
                ('id_rodzaju', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'rodzaje_lekow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seniorzy',
            fields=[
                ('id_seniora', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pesel', models.CharField(blank=True, max_length=11, null=True)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('zdjecie', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seniorzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SqlplusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('userid', models.CharField(blank=True, max_length=128, null=True)),
                ('attribute', models.CharField(blank=True, max_length=240, null=True)),
                ('scope', models.CharField(blank=True, max_length=240, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('char_value', models.CharField(blank=True, max_length=240, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('long_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sqlplus_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stanowiska',
            fields=[
                ('id_stanowiska', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'stanowiska',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wplaty',
            fields=[
                ('id_wplaty', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rodzaj', models.CharField(max_length=1)),
                ('konto_nadawcy', models.CharField(blank=True, max_length=26, null=True)),
            ],
            options={
                'db_table': 'wplaty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wynagrodzenia',
            fields=[
                ('id_wynagrodzenia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('kwota_podstawowa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kwota_dodatkowa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'wynagrodzenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wyposazenie',
            fields=[
                ('id_wyposazenia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('ilosc', models.BigIntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'wyposazenie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WyposazeniePokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wyposazenie_pokoj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracownicyKategorie',
            fields=[
                ('id_pracownika', models.OneToOneField(db_column='id_pracownika', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.pracownicy')),
            ],
            options={
                'db_table': 'pracownicy_kategorie',
                'managed': False,
            },
        ),
    ]
