# Generated by Django 3.2.2 on 2021-05-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osobakontaktowasenior',
            options={},
        ),
    ]
