# Generated by Django 3.2.2 on 2021-05-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_osobakontaktowasenior_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osobakontaktowasenior',
            name='id',
        ),
        migrations.AddField(
            model_name='osobakontaktowasenior',
            name='id_osobykontaktowejseniora',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
