from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Adresy)
admin.site.register(DomySeniora)
admin.site.register(KartyZdrowia)
admin.site.register(KategoriePrawaJazdy)
admin.site.register(Leki)
admin.site.register(Lozka)
admin.site.register(Marki)
admin.site.register(Modele)
admin.site.register(OsobaKontaktowaSenior)
admin.site.register(OsobyKontaktowe)
admin.site.register(Poczty)
admin.site.register(Pojazdy)
admin.site.register(Pokoje)
admin.site.register(Pracownicy)
admin.site.register(PracownicyKategorie)
admin.site.register(PrzyjmowaneLeki)
admin.site.register(RodzajeLekow)
admin.site.register(Seniorzy)
admin.site.register(Stanowiska)
admin.site.register(Wplaty)
admin.site.register(Wynagrodzenia)
admin.site.register(Wyposazenie)
admin.site.register(WyposazeniePokoj)